name: Test

on: [ pull_request, push ]

jobs:
  test:
    name: Check that the unut test are all passing
    runs-on: ubuntu-20.04
    steps:
      - name: Docker
        run: docker run -d --name webserver -p 80:80 nginx:1.21.1

